
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://web-study.ckxj9ziinanv.ap-northeast-2.rds.amazonaws.com:3306/todolist?useUnicode=true&characterEncoding=UTF-08"
    username: "admin"
    password: "1q2w3e4r"
#  main:
#    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 644050543123-ut81i5e8tpk6fdakuj7cb0b8efjhbea3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: aaLLOPj667_ePH6kY3IH
            client-secret: BbwKufOM6V
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: 1885cd7f127ef93f1cbaa1421a5cff35
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원 정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


mybatis:
  mapper-locations:
    - /mappers/*.xml